apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: ecommerce-local
type: Opaque
stringData:
  APP_KEY: "base64:K7GeJpLOtYrjW0A6VX+/OSpvmzOBitCefZlD72pim/A="
  DB_USERNAME: "ecommerce_user"
  DB_PASSWORD: "CHANGE_ME_DB_PASSWORD"
  DB_ROOT_PASSWORD: "CHANGE_ME_ROOT_PASSWORD"
