apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-local
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DimaMaimesko/e-comerce.git
    targetRevision: staging-gitops
    path: k8s/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
