apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce-local
resources:
  - app-deployment.yaml
  - app-service.yaml
  - queue-deployment.yaml
  - scheduler-deployment.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - mysql-pvc.yaml
  - ingress.yaml
  - jobs/migrate-job.yaml
