apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: queue
          image: ecommerce-k8s-local:latest
          imagePullPolicy: IfNotPresent
          command: ["php", "artisan", "queue:work", "--tries=3", "--timeout=90", "--sleep=3"]
          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-secret
