apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: ecommerce-staging
type: Opaque
stringData:
  APP_KEY: "PLACEHOLDER_WILL_BE_MANAGED_VIA_KUBECTL"
  DB_USERNAME: "PLACEHOLDER"
  DB_PASSWORD: "PLACEHOLDER"
  DB_ROOT_PASSWORD: "PLACEHOLDER"
